SUPPORTED = ("pt", "en")

_EN = {
    # Nav
    "Filamentos":         "Filaments",
    "Spools":             "Spools",
    "Carretéis":          "Empty Spools",
    "Carretéis Vazios":   "Empty Spools",
    "Pesar":              "Weigh",
    "Relatórios":         "Reports",
    "Por Material":       "By Material",
    "Por Local":          "By Location",
    "Estoque Baixo":      "Low Stock",
    "Histórico de Peso":  "Weight History",
    "Fila de Etiquetas":  "Label Queue",
    "Admin":              "Admin",
    "Usuários":           "Users",
    "Marcas / Logos":     "Brands / Logos",
    "Configurações":      "Settings",
    "Buscar...":          "Search...",
    "Sair":               "Logout",
    "Tema":               "Theme",

    # Updates
    "Atualizações":         "Updates",
    "Nova":                 "New",
    "Versão atual":         "Current version",
    "Última versão":        "Latest version",
    "não verificada":       "not checked",
    "Não foi possível verificar a última versão no GitHub. Tente novamente mais tarde.":
        "Could not check the latest version on GitHub. Try again later.",
    "Atualização disponível": "Update available",
    "Ver novidades":        "See what's new",
    "Atualizar agora":      "Update now",
    "Sistema atualizado":   "System up to date",
    "Atualizando… o serviço será reiniciado, aguarde.":
        "Updating… the service will restart, please wait.",
    "A atualização baixa a última release publicada e reinicia o serviço. Pode levar 1–2 minutos.":
        "The update downloads the latest published release and restarts the service. It may take 1–2 minutes.",
    "Concluído! Recarregando…": "Done! Reloading…",
    "Falha ao iniciar a atualização": "Failed to start the update",

    # Backup / restore
    "Backup":               "Backup",
    "Backup e restauração": "Backup & restore",
    "Fazer backup":         "Create backup",
    "Baixar backup":        "Download backup",
    "Restaurar backup":     "Restore backup",
    "Baixa um arquivo .zip com o banco de dados (filamentos, spools, usuários, configurações) e os logos das marcas. Guarde-o em local seguro.":
        "Downloads a .zip with the database (filaments, spools, users, settings) and brand logos. Keep it somewhere safe.",
    "A restauração substitui TODOS os dados atuais (incluindo usuários e senhas) pelos do arquivo. Não há como desfazer.":
        "Restoring replaces ALL current data (including users and passwords) with the file's contents. This cannot be undone.",
    "Selecione um arquivo .zip gerado por este sistema.":
        "Select a .zip file generated by this system.",
    "Tem certeza? Todos os dados atuais serão substituídos.":
        "Are you sure? All current data will be replaced.",
    "Após reinstalar o sistema, restaure aqui o último backup para recuperar tudo.":
        "After reinstalling the system, restore your latest backup here to recover everything.",

    # Lists — headers
    "Material":           "Material",
    "Marca":              "Brand",
    "Família":            "Family",
    "Spools Ativos":      "Active Spools",
    "Total":              "Total",
    "Local":              "Location",
    "Peso Atual":         "Current Weight",
    "Status":             "Status",
    "Nominal":            "Nominal",
    "Marca / Família":    "Brand / Family",

    # Filaments list
    "Filtrar...":                    "Filter...",
    "+ Novo Filamento":              "+ New Filament",
    "Novo Filamento":                "New Filament",
    "Filamento":                     "Filament",
    "Nenhum filamento cadastrado":   "No filaments registered",
    "Duplicar filamento":            "Duplicate filament",
    "Remover filamento":             "Delete filament",

    # Spools list
    "todos":                "all",
    "Ver finalizados":      "View finished",
    "Só ativos":            "Active only",
    "Fila: Todos":          "Queue: All",
    "Todos":                "All",
    "+ Novo Spool":         "+ New Spool",
    "Novo Spool":           "New Spool",
    "Nenhum spool encontrado": "No spools found",

    # Filament detail
    "Diâmetro":                  "Diameter",
    "Notas":                     "Notes",
    "Carretel Vazio":            "Empty Spool",
    "Nenhum spool cadastrado":   "No spools registered",
    "Ativo":                     "Active",
    "Finalizado":                "Finished",

    # Buttons
    "Ver":       "View",
    "Editar":    "Edit",
    "Salvar":    "Save",
    "Cancelar":  "Cancel",
    "Registrar": "Register",
    "Finalizar Spool": "Finish Spool",

    # Weigh modal
    "Peso bruto (g)":               "Gross weight (g)",
    "Erro de rede. Tente novamente.": "Network error. Please try again.",
    "% disponível":                 "% available",
    "% de estoque disponível":      "% stock available",

    # Tooltips / misc
    "Adicionar à fila":  "Add to queue",
    "Remover da fila":   "Remove from queue",

    # Reports
    "Relatório por Material":  "Report by Material",
    "Relatório por Local":     "Report by Location",
    "Histórico":               "History",
}


def get_translator(lang: str):
    table = _EN if lang == "en" else {}

    def _(s: str) -> str:
        return table.get(s, s)

    return _
