SUPPORTED = ("pt", "en", "es")

_EN = {
    # ── Nav ──────────────────────────────────────────────────────────────────
    "Filamentos":         "Filaments",
    "Spools":             "Spools",
    "Carretéis":          "Empty Spools",
    "Carretéis Vazios":   "Empty Spools",
    "Pesar":              "Weigh",
    "Relatórios":         "Reports",
    "Por Material":       "By Material",
    "Por Local":          "By Location",
    "Estoque Baixo":      "Low Stock",
    "Histórico de Peso":  "Weight History",
    "Fila de Etiquetas":  "Label Queue",
    "Estatísticas":       "Statistics",
    "Inventário":         "Inventory",
    "Admin":              "Admin",
    "Usuários":           "Users",
    "Marcas / Logos":              "Brands / Logos",
    "Nova Marca":                  "New Brand",
    "Nome da Marca":               "Brand Name",
    "Remover marca":               "Remove brand",
    "Remover a marca":             "Remove brand",
    "Buscar logo":                 "Fetch logo",
    "Nenhuma marca cadastrada.":   "No brands registered.",
    "Marca '{brand}' adicionada":              "Brand '{brand}' added",
    "Marca '{brand}' adicionada com logo":     "Brand '{brand}' added with logo",
    "Marca '{brand}' adicionada (logo não encontrado)": "Brand '{brand}' added (logo not found)",
    "Domínio":                                 "Domain",
    "opcional":                                "optional",
    "Se preenchido, busca o logo automaticamente.": "If filled, fetches the logo automatically.",
    "Marca removida":              "Brand removed",
    "Nome da marca é obrigatório": "Brand name is required",
    "Marca possui filamentos vinculados — remova-os antes": "Brand has linked filaments — remove them first",
    "Configurações":      "Settings",
    "Buscar...":          "Search...",
    "Sair":               "Logout",
    "Tema":               "Theme",
    "Login":              "Login",
    "Entrar":             "Sign in",
    "Manter conectado":   "Keep me signed in",

    # ── Updates ──────────────────────────────────────────────────────────────
    "Atualizações":         "Updates",
    "Nova":                 "New",
    "Versão atual":         "Current version",
    "Última versão":        "Latest version",
    "não verificada":       "not checked",
    "Não foi possível verificar a última versão no GitHub. Tente novamente mais tarde.":
        "Could not check the latest version on GitHub. Try again later.",
    "Atualização disponível": "Update available",
    "Ver novidades":        "See what's new",
    "Novidades da v{v}":    "What's new in v{v}",
    "Atualizar agora":      "Update now",
    "Sistema atualizado":   "System up to date",
    "Atualizado para a v{v} com sucesso": "Successfully updated to v{v}",
    "Atualizando… o serviço será reiniciado, aguarde.":
        "Updating… the service will restart, please wait.",
    "A atualização baixa a última release publicada e reinicia o serviço. Pode levar 1–2 minutos.":
        "The update downloads the latest published release and restarts the service. It may take 1–2 minutes.",
    "Concluído! Recarregando…": "Done! Reloading…",
    "Falha ao iniciar a atualização": "Failed to start the update",

    # ── Backup / restore ─────────────────────────────────────────────────────
    "Backup":               "Backup",
    "Backup e restauração": "Backup & restore",
    "Fazer backup":         "Create backup",
    "Baixar backup":        "Download backup",
    "Baixar":               "Download",
    "Restaurar backup":     "Restore backup",
    "Baixa um arquivo .zip com o banco de dados (filamentos, spools, usuários, configurações) e os logos das marcas. Guarde-o em local seguro.":
        "Downloads a .zip with the database (filaments, spools, users, settings) and brand logos. Keep it somewhere safe.",
    "A restauração substitui TODOS os dados atuais (incluindo usuários e senhas) pelos do arquivo. Não há como desfazer.":
        "Restoring replaces ALL current data (including users and passwords) with the file's contents. This cannot be undone.",
    "Selecione um arquivo .zip gerado por este sistema.":
        "Select a .zip file generated by this system.",
    "Tem certeza? Todos os dados atuais serão substituídos.":
        "Are you sure? All current data will be replaced.",
    "Após reinstalar o sistema, restaure aqui o último backup para recuperar tudo.":
        "After reinstalling the system, restore your latest backup here to recover everything.",

    # ── Headers / common ─────────────────────────────────────────────────────
    "Material":           "Material",
    "Marca":              "Brand",
    "Marcas":             "Brands",
    "Materiais":          "Materials",
    "Famílias de cor":    "Color families",
    "Família":            "Family",
    "Spools Ativos":      "Active Spools",
    "Total":              "Total",
    "Local":              "Location",
    "Peso":               "Weight",
    "Peso Atual":         "Current Weight",
    "Status":             "Status",
    "Nominal":            "Nominal",
    "Marca / Família":    "Brand / Family",
    "Nome":               "Name",
    "Data/Hora":          "Date/Time",
    "Bruto (g)":          "Gross (g)",
    "Tara (g)":           "Tare (g)",
    "Net (g)":            "Net (g)",
    "Sem dados":          "No data",
    "ativos":             "active",
    "total":              "total",

    # ── Filaments ────────────────────────────────────────────────────────────
    "Filtrar...":                    "Filter...",
    "+ Novo Filamento":              "+ New Filament",
    "Novo Filamento":                "New Filament",
    "Editar Filamento":              "Edit Filament",
    "Filamento":                     "Filament",
    "Importar do catálogo":          "Import from catalog",
    "Buscar no catálogo de filamentos": "Search the filament catalog",
    "Buscar por marca, material ou cor...": "Search by brand, material or color...",
    "Nenhum filamento encontrado":   "No filament found",
    "Digite para buscar no catálogo.": "Type to search the catalog.",
    "Refine a busca para ver mais.":  "Refine your search to see more.",
    "Fonte: catálogo aberto SpoolmanDB (MIT)": "Source: SpoolmanDB open catalog (MIT)",
    "Fechar":                        "Close",
    "Nenhum filamento cadastrado":   "No filaments registered",
    "Duplicar filamento":            "Duplicate filament",
    "Remover filamento":             "Delete filament",
    "Remover o filamento":           "Delete filament",
    "spool(s) vinculado(s) — remova-os antes de excluir":
        "linked spool(s) — remove them before deleting",
    "ex: Basic, Matte, Rapid, HS":   "e.g.: Basic, Matte, Rapid, HS",
    "Cor (hex)":                     "Color (hex)",
    "Nome da Cor":                   "Color Name",
    "ex: Galaxy Black, Azul Cobalto, Silk Silver": "e.g.: Galaxy Black, Cobalt Blue, Silk Silver",
    "Nome do fabricante ou como você identifica esta cor. Usado na etiqueta impressa.":
        "Manufacturer name or how you identify this color. Used on the printed label.",
    "Diâmetro (mm)":                 "Diameter (mm)",
    "Pesquise ou digite...":         "Search or type...",
    "Remover este filamento?":       "Remove this filament?",
    "Diâmetro":                      "Diameter",
    "Notas":                         "Notes",
    "Carretel Vazio":                "Empty Spool",
    "Ativo":                         "Active",
    "Finalizado":                    "Finished",

    # ── Spools ───────────────────────────────────────────────────────────────
    "todos":                "all",
    "Ver finalizados":      "View finished",
    "Só ativos":            "Active only",
    "Fila: Todos":          "Queue: All",
    "Todos":                "All",
    "+ Novo Spool":         "+ New Spool",
    "Novo Spool":           "New Spool",
    "Editar Spool":         "Edit Spool",
    "Finalizar Spool":      "Finish Spool",
    "Marcar spool como finalizado?": "Mark spool as finished?",
    "Nenhum spool encontrado": "No spools found",
    "Nenhum spool cadastrado":   "No spools registered",
    "Filtrar por Spool":    "Filter by Spool",
    "Todos os spools":      "All spools",
    "Spool":                "Spool",
    "Código do Spool":      "Spool Code",
    "Ver todos os spools":  "View all spools",
    "Nenhum spool abaixo do threshold configurado.": "No spool below the configured threshold.",
    "Adicione spools pela página de detalhe ou ao cadastrar um novo.":
        "Add spools from the detail page or when registering a new one.",
    "Use a barra de busca no topo para pesquisar spools e filamentos.":
        "Use the search bar at the top to look up spools and filaments.",
    "Detalhe do Spool":     "Spool detail",
    # Spool form
    "Selecione um filamento...":   "Select a filament...",
    "Editar cor / filamento":      "Edit color / filament",
    "Modelo de Carretel Vazio":    "Empty Spool Model",
    "Tara personalizada / desconhecida": "Custom / unknown tare",
    "Tara Personalizada (g)":      "Custom Tare (g)",
    "Deixe em branco se usar o modelo acima": "Leave blank if using the model above",
    "Deixe em branco se usar o modelo ao lado": "Leave blank if using the model to the left",
    "Peso Nominal do Filamento (g)": "Nominal Filament Weight (g)",
    "Peso declarado na embalagem (ex: 1000g).": "Weight stated on the package (e.g.: 1000g).",
    "Local de Armazenamento":      "Storage Location",
    "ex: Gaveta A3, Prateleira 2": "e.g.: Drawer A3, Shelf 2",
    "Data de Compra":              "Purchase Date",
    "Preço":                       "Price",
    "(sem cor)":                   "(no color)",
    "Tara do modelo":              "Model tare",

    # ── Weigh ────────────────────────────────────────────────────────────────
    "Registrar Peso":              "Record Weight",
    "Tara do carretel":            "Spool tare",
    "Último peso registrado":      "Last recorded weight",
    "Peso Bruto na Balança (g)":   "Gross Weight on Scale (g)",
    "ex: 1182":                    "e.g.: 1182",
    "Peso do rolo completo (filamento + carretel vazio).": "Weight of the full roll (filament + empty spool).",
    "de filamento disponível":     "of filament available",
    "Notas (opcional)":            "Notes (optional)",
    "ex: pré-impressão longa":     "e.g.: long pre-print",
    "Salvar Pesagem":              "Save Weighing",
    "de tara":                     "of tare",
    "Pesagem Rápida":              "Quick Weigh",
    "Aceita SP-0001, SP0001 ou somente o número.": "Accepts SP-0001, SP0001 or just the number.",
    "Peso Bruto (g)":              "Gross Weight (g)",
    "Peso total com o carretel. A tara é subtraída automaticamente.":
        "Total weight with the spool. Tare is subtracted automatically.",

    # ── Weigh modal ──────────────────────────────────────────────────────────
    "Peso bruto (g)":               "Gross weight (g)",
    "Erro de rede. Tente novamente.": "Network error. Please try again.",
    "% disponível":                 "% available",
    "% de estoque disponível":      "% stock available",
    "Registrar":                    "Register",

    # ── Label queue / printing ───────────────────────────────────────────────
    "Imprimir":             "Print",
    "Imprimir PDF":         "Print PDF",
    "Imprimir Niimbot":     "Print Niimbot",
    "Imprimir Tudo":        "Print All",
    "Limpar Fila":          "Clear Queue",
    "Nenhuma etiqueta na fila.": "No labels in the queue.",
    "Após imprimir, você pode limpar a fila clicando em \"Limpar Fila\".":
        "After printing, you can clear the queue by clicking \"Clear Queue\".",

    # ── Dashboard ────────────────────────────────────────────────────────────
    "Dashboard":          "Dashboard",
    "Restante":           "Remaining",
    "Pesagens Recentes":  "Recent Weighings",
    "Quando":             "When",
    "Peso Net":           "Net Weight",

    # ── Buttons ──────────────────────────────────────────────────────────────
    "Ver":       "View",
    "Editar":    "Edit",
    "Salvar":    "Save",
    "Cancelar":  "Cancel",
    "Remover":   "Remove",

    # ── Tooltips / misc ──────────────────────────────────────────────────────
    "Adicionar à fila":  "Add to queue",
    "Remover da fila":   "Remove from queue",
    "Sem local":         "No location set",

    # ── Reports ──────────────────────────────────────────────────────────────
    "Relatório por Material":  "Report by Material",
    "Relatório por Local":     "Report by Location",
    "Histórico":               "History",
    "Histórico de Pesagens":   "Weighing History",
    "Filtrar por Filamento":   "Filter by Filament",
    "Todos os filamentos":     "All filaments",
    "Filtrar":                 "Filter",
    "Limpar":                  "Clear",
    "Nenhuma pesagem registrada": "No weighings recorded",
    "Estoque por Material":    "Stock by Material",
    "Estoque por Local":       "Stock by Location",
    "Total Net (g)":           "Total Net (g)",
    "Total Net (kg)":          "Total Net (kg)",
    "Nominal (kg)":            "Nominal (kg)",
    "Distribuição":            "Distribution",
    "Critério: peso atual":    "Criteria: current weight",
    "OU":                      "OR",
    "do nominal.":             "of nominal.",
    "Ajustar threshold":       "Adjust threshold",
    "Busca":                   "Search",
    "Resultados para":         "Results for",
    "Nenhum resultado encontrado para": "No results found for",

    # ── Admin: users ─────────────────────────────────────────────────────────
    "Gerenciamento de Usuários": "User Management",
    "Novo Usuário":              "New User",
    "Usuário":                   "User",
    "Senha":                     "Password",
    "Perfil":                    "Role",
    "Viewer (somente leitura)":  "Viewer (read only)",
    "Admin (acesso total)":      "Admin (full access)",
    "Criar Usuário":             "Create User",
    "Usuários Cadastrados":      "Registered Users",
    "Criado em":                 "Created on",
    "você":                      "you",
    "Alterar senha de":          "Change password for",
    "Nova senha":                "New password",

    # ── Admin: brands ────────────────────────────────────────────────────────
    "Informe o domínio da marca para buscar o logo automaticamente via":
        "Enter the brand domain to fetch the logo automatically via",
    "e salvar localmente. Ou faça upload manual de um arquivo PNG/JPG/SVG.":
        "and save it locally. Or upload a PNG/JPG/SVG file manually.",
    "filamento(s)":              "filament(s)",
    "ex: bambulab.com":          "e.g.: bambulab.com",
    "Upload":                    "Upload",
    "Nenhuma marca cadastrada. Adicione filamentos primeiro.":
        "No brands registered. Add filaments first.",

    # ── Admin: settings ──────────────────────────────────────────────────────
    "Configurações do Sistema":  "System Settings",
    "Geral":                     "General",
    "Moeda":                     "Currency",
    "Símbolo e formato usados nos preços. Independente do idioma da interface.":
        "Symbol and format used for prices. Independent of the interface language.",
    "URL Base do Sistema":       "System Base URL",
    "Usada para gerar o QR code nas etiquetas. Deve ser acessível pelo celular.":
        "Used to generate the QR code on labels. Must be reachable from the phone.",
    "Threshold (g)":             "Threshold (g)",
    "Threshold (%)":             "Threshold (%)",
    "Peso mínimo antes de sinalizar.": "Minimum weight before flagging.",
    "Porcentagem mínima do nominal.":  "Minimum percentage of nominal.",
    "Etiquetas":                 "Labels",
    "Largura":                   "Width",
    "Altura":                    "Height",
    "Tamanho do PDF gerado para impressão térmica. Padrão:":
        "Size of the PDF generated for thermal printing. Default:",
    "Fontes e QR code escalam automaticamente.": "Fonts and QR code scale automatically.",
    "Impressão Direta (Niimbot)": "Direct Printing (Niimbot)",
    "Modelo da impressora":      "Printer model",
    "Tamanho da etiqueta":       "Label size",
    "Usado pelo botão":          "Used by the button",
    "(Web Bluetooth, direto do navegador). Requer Chrome/Edge em HTTPS. Não afeta o PDF acima.":
        "(Web Bluetooth, straight from the browser). Requires Chrome/Edge over HTTPS. Does not affect the PDF above.",
    "Um item só para todas as Niimbot — o app identifica o modelo conectado (B1, B1 Pro ou M2-H) e envia a resolução certa automaticamente.":
        "One item for all Niimbots — the app detects the connected model (B1, B1 Pro or M2-H) and sends the right resolution automatically.",
    # Niimbot — mensagens client-side (driver vendorado é só em inglês; tradução aqui)
    "identificando impressora…":  "identifying printer…",
    "imprimindo…":                "printing…",
    "Impresso":                   "Printed",
    "Nenhuma impressora selecionada.": "No printer selected.",
    "Falha na impressão.":        "Print failed.",
    "Use Chrome ou Edge em HTTPS para imprimir direto na Niimbot.":
        "Use Chrome or Edge over HTTPS to print straight to the Niimbot.",
    "Impressora não reconhecida ({printer}). Atualize o app ou reporte.":
        "Unrecognized printer ({printer}). Update the app or report it.",
    "Salvar Configurações":      "Save Settings",

    # ── Error page ───────────────────────────────────────────────────────────
    "Erro":                      "Error",
    "Voltar ao início":          "Back to home",
    "Acesso negado":             "Access denied",
    "Página não encontrada":     "Page not found",
    "Requisição inválida":              "Invalid request",
    "Erro interno do servidor":         "Internal server error",
    "Erro ao processar. Tente novamente.": "Processing error. Please try again.",

    # ── Spool models ─────────────────────────────────────────────────────────
    "+ Novo Modelo":             "+ New Model",
    "Cadastre os modelos de carretel vazio para que o sistema possa calcular o peso real de filamento disponível.":
        "Register empty spool models so the system can calculate the real available filament weight.",
    "Tara (g)":                  "Tare (g)",
    "Nenhum modelo cadastrado":  "No models registered",
    "Editar Modelo":             "Edit Model",
    "Novo Modelo":               "New Model",
    "Novo Modelo de Carretel":   "New Spool Model",
    "ex: Bambu Lab Standard 1kg": "e.g.: Bambu Lab Standard 1kg",
    "Peso do Carretel Vazio (g)": "Empty Spool Weight (g)",
    "ex: 250":                   "e.g.: 250",
    "Pese o carretel físico sem filamento.": "Weigh the physical spool with no filament.",

    # ── Flash / mensagens do servidor ────────────────────────────────────────
    "Sessão expirada ou token inválido. Tente novamente.": "Session expired or invalid token. Please try again.",
    "Muitas tentativas. Aguarde {min} minutos e tente novamente.": "Too many attempts. Wait {min} minutes and try again.",
    "Usuário ou senha incorretos": "Incorrect username or password",
    "Filamento cadastrado com sucesso": "Filament registered successfully",
    "Filamento atualizado": "Filament updated",
    "Filamento duplicado — editando cópia": "Filament duplicated — editing copy",
    "Filamento removido": "Filament removed",
    "Filamento possui spools associados": "Filament has associated spools",
    "Modelo de carretel cadastrado": "Spool model registered",
    "Modelo atualizado": "Model updated",
    "Modelo removido": "Model removed",
    "Modelo em uso por spools existentes": "Model in use by existing spools",
    "Rolo cadastrado com sucesso": "Spool registered successfully",
    "Rolo atualizado": "Spool updated",
    "Rolo marcado como finalizado": "Spool marked as finished",
    "Peso bruto ({g:.0f}g) menor que tara ({t:.0f}g). Verifique.": "Gross weight ({g:.0f}g) lower than tare ({t:.0f}g). Please check.",
    "Peso registrado: {n:.0f}g de filamento": "Weight recorded: {n:.0f}g of filament",
    "Valor inválido": "Invalid value",
    "Código de rolo inválido": "Invalid spool code",
    "Rolo SP-{code} não encontrado": "Spool SP-{code} not found",
    "Peso bruto inválido": "Invalid gross weight",
    "SP-{code} — {n:.0f}g de filamento (bruto {g:.0f}g − tara {t:.0f}g)": "SP-{code} — {n:.0f}g of filament (gross {g:.0f}g − tare {t:.0f}g)",
    "Adicionado à fila de impressão": "Added to the print queue",
    "{n} rolo(s) adicionado(s) à fila de impressão": "{n} spool(s) added to the print queue",
    "Fila vazia": "Queue empty",
    "{n} rolo(s) removido(s) da fila": "{n} spool(s) removed from the queue",
    "Fila limpa": "Queue cleared",
    "Usuário e senha são obrigatórios": "Username and password are required",
    "Usuário já existe": "User already exists",
    "Usuário {u} criado": "User {u} created",
    "Senha não pode ser vazia": "Password cannot be empty",
    "A senha precisa ter pelo menos {n} caracteres": "Password must be at least {n} characters long",
    "Senha atualizada": "Password updated",
    "Você não pode deletar seu próprio usuário": "You cannot delete your own user",
    "Usuário removido": "User removed",
    "Marca e domínio são obrigatórios": "Brand and domain are required",
    "Logo de '{brand}' baixado com sucesso": "Logo for '{brand}' downloaded successfully",
    "Não foi possível baixar o logo via Clearbit para '{domain}'": "Could not download the logo via Clearbit for '{domain}'",
    "Selecione um arquivo": "Select a file",
    "Arquivo inválido": "Invalid file",
    "Formato não suportado (PNG, JPG ou WEBP)": "Unsupported format (PNG, JPG or WEBP)",
    "Logo de '{brand}' salvo": "Logo for '{brand}' saved",
    "Configurações salvas": "Settings saved",
    "Selecione um arquivo de backup (.zip)": "Select a backup file (.zip)",
    "Arquivo inválido — não é um .zip de backup": "Invalid file — not a backup .zip",
    "Backup inválido: spool.db ausente no arquivo": "Invalid backup: spool.db missing in the file",
    "Backup inválido: o banco não tem a estrutura do Spool Control": "Invalid backup: the database doesn't have the Spool Control structure",
    "Backup restaurado com sucesso ({n} logo(s)). Recomendado sair e entrar novamente.": "Backup restored successfully ({n} logo(s)). It's recommended to log out and back in.",

    # ── 2FA (verificação em duas etapas) ─────────────────────────────────────
    "Verificação em duas etapas":     "Two-factor authentication",
    "Verificar":                      "Verify",
    "Cancelar":                       "Cancel",
    "Código de verificação":          "Verification code",
    "Código inválido":                "Invalid code",
    "Digite o código de 6 dígitos do seu app autenticador, ou um código de recuperação.":
        "Enter the 6-digit code from your authenticator app, or a recovery code.",
    "Verificação em duas etapas ativada":   "Two-factor authentication enabled",
    "Verificação em duas etapas desativada": "Two-factor authentication disabled",
    "Novos códigos de recuperação gerados": "New recovery codes generated",
    "Sessão expirada. Tente novamente.":    "Session expired. Please try again.",
    "Códigos de recuperação":               "Recovery codes",
    "Guarde estes códigos em local seguro. Cada um serve UMA vez se você perder o acesso ao app autenticador. Eles NÃO serão mostrados novamente.":
        "Store these codes somewhere safe. Each works ONCE if you lose access to your authenticator app. They will NOT be shown again.",
    "A verificação em duas etapas está ativa nesta conta.":
        "Two-factor authentication is active on this account.",
    "Códigos de recuperação restantes:":    "Recovery codes remaining:",
    "Regenerar códigos de recuperação":     "Regenerate recovery codes",
    "Gera 8 códigos novos e invalida os antigos. Use se acabaram ou se você os perdeu.":
        "Generates 8 new codes and invalidates the old ones. Use if you ran out or lost them.",
    "Regenerar":                            "Regenerate",
    "Desativar 2FA":                        "Disable 2FA",
    "Adicione uma camada extra de segurança ao login: além da senha, será pedido um código gerado por um app autenticador (Google Authenticator, Authy, FreeOTP…).":
        "Add an extra layer of login security: besides your password, you'll be asked for a code from an authenticator app (Google Authenticator, Authy, FreeOTP…).",
    "Ativar verificação em duas etapas":    "Enable two-factor authentication",
    "Escaneie o QR Code abaixo com o seu app autenticador.":
        "Scan the QR code below with your authenticator app.",
    "Digite o código de 6 dígitos exibido pelo app para confirmar.":
        "Enter the 6-digit code shown by the app to confirm.",
    "Não consegue escanear? Use esta chave:": "Can't scan? Use this key:",
    "Ativar":                               "Enable",
    "Copiar códigos":                       "Copy codes",
    "Copiado!":                             "Copied!",
    "Proteja sua conta com verificação em duas etapas":
        "Protect your account with two-factor authentication",
    "Você pode ativar agora ou depois, na sua conta.":
        "You can enable it now or later, from your account.",
    "Agora não":                            "Not now",
    "Ativar agora":                         "Enable now",

    # ── Color buckets (stats) ────────────────────────────────────────────────
    "Preto":    "Black",
    "Branco":   "White",
    "Cinza":    "Gray",
    "Vermelho": "Red",
    "Laranja":  "Orange",
    "Amarelo":  "Yellow",
    "Verde":    "Green",
    "Ciano":    "Cyan",
    "Azul":     "Blue",
    "Roxo":     "Purple",
    "Rosa":     "Pink",
    "Marrom":   "Brown",
}

_ES = {
    # ── Nav ──────────────────────────────────────────────────────────────────
    "Filamentos":         "Filamentos",
    "Spools":             "Bobinas",
    "Carretéis":          "Carretes Vacíos",
    "Carretéis Vazios":   "Carretes Vacíos",
    "Pesar":              "Pesar",
    "Relatórios":         "Informes",
    "Por Material":       "Por Material",
    "Por Local":          "Por Ubicación",
    "Estoque Baixo":      "Stock Bajo",
    "Histórico de Peso":  "Historial de Peso",
    "Fila de Etiquetas":  "Cola de Etiquetas",
    "Estatísticas":       "Estadísticas",
    "Inventário":         "Inventario",
    "Admin":              "Admin",
    "Usuários":           "Usuarios",
    "Marcas / Logos":              "Marcas / Logos",
    "Nova Marca":                  "Nueva Marca",
    "Nome da Marca":               "Nombre de Marca",
    "Remover marca":               "Eliminar marca",
    "Remover a marca":             "Eliminar la marca",
    "Buscar logo":                 "Buscar logo",
    "Nenhuma marca cadastrada.":   "Ninguna marca registrada.",
    "Marca '{brand}' adicionada":              "Marca '{brand}' agregada",
    "Marca '{brand}' adicionada com logo":     "Marca '{brand}' agregada con logo",
    "Marca '{brand}' adicionada (logo não encontrado)": "Marca '{brand}' agregada (logo no encontrado)",
    "Domínio":                                 "Dominio",
    "opcional":                                "opcional",
    "Se preenchido, busca o logo automaticamente.": "Si se completa, busca el logo automáticamente.",
    "Marca removida":              "Marca eliminada",
    "Nome da marca é obrigatório": "El nombre de la marca es obligatorio",
    "Marca possui filamentos vinculados — remova-os antes": "La marca tiene filamentos vinculados — elimínelos primero",
    "Configurações":      "Ajustes",
    "Buscar...":          "Buscar...",
    "Sair":               "Salir",
    "Tema":               "Tema",
    "Login":              "Iniciar sesión",
    "Entrar":             "Entrar",
    "Manter conectado":   "Mantener la sesión iniciada",

    # ── Updates ──────────────────────────────────────────────────────────────
    "Atualizações":         "Actualizaciones",
    "Nova":                 "Nueva",
    "Versão atual":         "Versión actual",
    "Última versão":        "Última versión",
    "não verificada":       "no verificada",
    "Não foi possível verificar a última versão no GitHub. Tente novamente mais tarde.":
        "No se pudo verificar la última versión en GitHub. Inténtalo de nuevo más tarde.",
    "Atualização disponível": "Actualización disponible",
    "Ver novidades":        "Ver novedades",
    "Novidades da v{v}":    "Novedades de la v{v}",
    "Atualizar agora":      "Actualizar ahora",
    "Sistema atualizado":   "Sistema actualizado",
    "Atualizado para a v{v} com sucesso": "Actualizado a la v{v} con éxito",
    "Atualizando… o serviço será reiniciado, aguarde.":
        "Actualizando… el servicio se reiniciará, espera.",
    "A atualização baixa a última release publicada e reinicia o serviço. Pode levar 1–2 minutos.":
        "La actualización descarga la última versión publicada y reinicia el servicio. Puede tardar 1–2 minutos.",
    "Concluído! Recarregando…": "¡Listo! Recargando…",
    "Falha ao iniciar a atualização": "Error al iniciar la actualización",

    # ── Backup / restore ─────────────────────────────────────────────────────
    "Backup":               "Copia de seguridad",
    "Backup e restauração": "Copia y restauración",
    "Fazer backup":         "Crear copia",
    "Baixar backup":        "Descargar copia",
    "Baixar":               "Descargar",
    "Restaurar backup":     "Restaurar copia",
    "Baixa um arquivo .zip com o banco de dados (filamentos, spools, usuários, configurações) e os logos das marcas. Guarde-o em local seguro.":
        "Descarga un .zip con la base de datos (filamentos, bobinas, usuarios, ajustes) y los logos de marcas. Guárdalo en un lugar seguro.",
    "A restauração substitui TODOS os dados atuais (incluindo usuários e senhas) pelos do arquivo. Não há como desfazer.":
        "La restauración reemplaza TODOS los datos actuales (incluidos usuarios y contraseñas) por los del archivo. No se puede deshacer.",
    "Selecione um arquivo .zip gerado por este sistema.":
        "Selecciona un archivo .zip generado por este sistema.",
    "Tem certeza? Todos os dados atuais serão substituídos.":
        "¿Seguro? Todos los datos actuales serán reemplazados.",
    "Após reinstalar o sistema, restaure aqui o último backup para recuperar tudo.":
        "Tras reinstalar el sistema, restaura aquí la última copia para recuperar todo.",

    # ── Headers / common ─────────────────────────────────────────────────────
    "Material":           "Material",
    "Marca":              "Marca",
    "Marcas":             "Marcas",
    "Materiais":          "Materiales",
    "Famílias de cor":    "Familias de color",
    "Família":            "Familia",
    "Spools Ativos":      "Bobinas Activas",
    "Total":              "Total",
    "Local":              "Ubicación",
    "Peso":               "Peso",
    "Peso Atual":         "Peso Actual",
    "Status":             "Estado",
    "Nominal":            "Nominal",
    "Marca / Família":    "Marca / Familia",
    "Nome":               "Nombre",
    "Data/Hora":          "Fecha/Hora",
    "Bruto (g)":          "Bruto (g)",
    "Tara (g)":           "Tara (g)",
    "Net (g)":            "Neto (g)",
    "Sem dados":          "Sin datos",
    "ativos":             "activas",
    "total":              "total",

    # ── Filaments ────────────────────────────────────────────────────────────
    "Filtrar...":                    "Filtrar...",
    "+ Novo Filamento":              "+ Nuevo Filamento",
    "Novo Filamento":                "Nuevo Filamento",
    "Editar Filamento":              "Editar Filamento",
    "Filamento":                     "Filamento",
    "Importar do catálogo":          "Importar del catálogo",
    "Buscar no catálogo de filamentos": "Buscar en el catálogo de filamentos",
    "Buscar por marca, material ou cor...": "Buscar por marca, material o color...",
    "Nenhum filamento encontrado":   "Ningún filamento encontrado",
    "Digite para buscar no catálogo.": "Escribe para buscar en el catálogo.",
    "Refine a busca para ver mais.":  "Refina la búsqueda para ver más.",
    "Fonte: catálogo aberto SpoolmanDB (MIT)": "Fuente: catálogo abierto SpoolmanDB (MIT)",
    "Fechar":                        "Cerrar",
    "Nenhum filamento cadastrado":   "Ningún filamento registrado",
    "Duplicar filamento":            "Duplicar filamento",
    "Remover filamento":             "Eliminar filamento",
    "Remover o filamento":           "Eliminar el filamento",
    "spool(s) vinculado(s) — remova-os antes de excluir":
        "bobina(s) vinculada(s) — elimínalas antes de borrar",
    "ex: Basic, Matte, Rapid, HS":   "ej.: Basic, Matte, Rapid, HS",
    "Cor (hex)":                     "Color (hex)",
    "Nome da Cor":                   "Nombre del Color",
    "ex: Galaxy Black, Azul Cobalto, Silk Silver": "ej.: Galaxy Black, Azul Cobalto, Silk Silver",
    "Nome do fabricante ou como você identifica esta cor. Usado na etiqueta impressa.":
        "Nombre del fabricante o cómo identificas este color. Se usa en la etiqueta impresa.",
    "Diâmetro (mm)":                 "Diámetro (mm)",
    "Pesquise ou digite...":         "Busca o escribe...",
    "Remover este filamento?":       "¿Eliminar este filamento?",
    "Diâmetro":                      "Diámetro",
    "Notas":                         "Notas",
    "Carretel Vazio":                "Carrete Vacío",
    "Ativo":                         "Activo",
    "Finalizado":                    "Finalizado",

    # ── Spools ───────────────────────────────────────────────────────────────
    "todos":                "todas",
    "Ver finalizados":      "Ver finalizadas",
    "Só ativos":            "Solo activas",
    "Fila: Todos":          "Cola: Todas",
    "Todos":                "Todas",
    "+ Novo Spool":         "+ Nueva Bobina",
    "Novo Spool":           "Nueva Bobina",
    "Editar Spool":         "Editar Bobina",
    "Finalizar Spool":      "Finalizar Bobina",
    "Marcar spool como finalizado?": "¿Marcar la bobina como finalizada?",
    "Nenhum spool encontrado": "Ninguna bobina encontrada",
    "Nenhum spool cadastrado":   "Ninguna bobina registrada",
    "Filtrar por Spool":    "Filtrar por Bobina",
    "Todos os spools":      "Todas las bobinas",
    "Spool":                "Bobina",
    "Código do Spool":      "Código de la Bobina",
    "Ver todos os spools":  "Ver todas las bobinas",
    "Nenhum spool abaixo do threshold configurado.": "Ninguna bobina por debajo del umbral configurado.",
    "Adicione spools pela página de detalhe ou ao cadastrar um novo.":
        "Agrega bobinas desde la página de detalle o al registrar una nueva.",
    "Use a barra de busca no topo para pesquisar spools e filamentos.":
        "Usa la barra de búsqueda de arriba para buscar bobinas y filamentos.",
    "Detalhe do Spool":     "Detalle de la bobina",
    # Spool form
    "Selecione um filamento...":   "Selecciona un filamento...",
    "Editar cor / filamento":      "Editar color / filamento",
    "Modelo de Carretel Vazio":    "Modelo de Carrete Vacío",
    "Tara personalizada / desconhecida": "Tara personalizada / desconocida",
    "Tara Personalizada (g)":      "Tara Personalizada (g)",
    "Deixe em branco se usar o modelo acima": "Deja en blanco si usas el modelo de arriba",
    "Deixe em branco se usar o modelo ao lado": "Deja en blanco si usas el modelo de al lado",
    "Peso Nominal do Filamento (g)": "Peso Nominal del Filamento (g)",
    "Peso declarado na embalagem (ex: 1000g).": "Peso indicado en el empaque (ej.: 1000g).",
    "Local de Armazenamento":      "Lugar de Almacenamiento",
    "ex: Gaveta A3, Prateleira 2": "ej.: Cajón A3, Estante 2",
    "Data de Compra":              "Fecha de Compra",
    "Preço":                       "Precio",
    "(sem cor)":                   "(sin color)",
    "Tara do modelo":              "Tara del modelo",

    # ── Weigh ────────────────────────────────────────────────────────────────
    "Registrar Peso":              "Registrar Peso",
    "Tara do carretel":            "Tara del carrete",
    "Último peso registrado":      "Último peso registrado",
    "Peso Bruto na Balança (g)":   "Peso Bruto en la Balanza (g)",
    "ex: 1182":                    "ej.: 1182",
    "Peso do rolo completo (filamento + carretel vazio).": "Peso del rollo completo (filamento + carrete vacío).",
    "de filamento disponível":     "de filamento disponible",
    "Notas (opcional)":            "Notas (opcional)",
    "ex: pré-impressão longa":     "ej.: preimpresión larga",
    "Salvar Pesagem":              "Guardar Pesaje",
    "de tara":                     "de tara",
    "Pesagem Rápida":              "Pesaje Rápido",
    "Aceita SP-0001, SP0001 ou somente o número.": "Acepta SP-0001, SP0001 o solo el número.",
    "Peso Bruto (g)":              "Peso Bruto (g)",
    "Peso total com o carretel. A tara é subtraída automaticamente.":
        "Peso total con el carrete. La tara se resta automáticamente.",

    # ── Weigh modal ──────────────────────────────────────────────────────────
    "Peso bruto (g)":               "Peso bruto (g)",
    "Erro de rede. Tente novamente.": "Error de red. Inténtalo de nuevo.",
    "% disponível":                 "% disponible",
    "% de estoque disponível":      "% de stock disponible",
    "Registrar":                    "Registrar",

    # ── Label queue / printing ───────────────────────────────────────────────
    "Imprimir":             "Imprimir",
    "Imprimir PDF":         "Imprimir PDF",
    "Imprimir Niimbot":     "Imprimir Niimbot",
    "Imprimir Tudo":        "Imprimir Todo",
    "Limpar Fila":          "Vaciar Cola",
    "Nenhuma etiqueta na fila.": "No hay etiquetas en la cola.",
    "Após imprimir, você pode limpar a fila clicando em \"Limpar Fila\".":
        "Después de imprimir, puedes vaciar la cola con \"Vaciar Cola\".",

    # ── Dashboard ────────────────────────────────────────────────────────────
    "Dashboard":          "Panel",
    "Restante":           "Restante",
    "Pesagens Recentes":  "Pesajes Recientes",
    "Quando":             "Cuándo",
    "Peso Net":           "Peso Neto",

    # ── Buttons ──────────────────────────────────────────────────────────────
    "Ver":       "Ver",
    "Editar":    "Editar",
    "Salvar":    "Guardar",
    "Cancelar":  "Cancelar",
    "Remover":   "Eliminar",

    # ── Tooltips / misc ──────────────────────────────────────────────────────
    "Adicionar à fila":  "Agregar a la cola",
    "Remover da fila":   "Quitar de la cola",
    "Sem local":         "Sin ubicación",

    # ── Reports ──────────────────────────────────────────────────────────────
    "Relatório por Material":  "Informe por Material",
    "Relatório por Local":     "Informe por Ubicación",
    "Histórico":               "Historial",
    "Histórico de Pesagens":   "Historial de Pesajes",
    "Filtrar por Filamento":   "Filtrar por Filamento",
    "Todos os filamentos":     "Todos los filamentos",
    "Filtrar":                 "Filtrar",
    "Limpar":                  "Limpiar",
    "Nenhuma pesagem registrada": "Ningún pesaje registrado",
    "Estoque por Material":    "Stock por Material",
    "Estoque por Local":       "Stock por Ubicación",
    "Total Net (g)":           "Neto Total (g)",
    "Total Net (kg)":          "Neto Total (kg)",
    "Nominal (kg)":            "Nominal (kg)",
    "Distribuição":            "Distribución",
    "Critério: peso atual":    "Criterio: peso actual",
    "OU":                      "O",
    "do nominal.":             "del nominal.",
    "Ajustar threshold":       "Ajustar umbral",
    "Busca":                   "Búsqueda",
    "Resultados para":         "Resultados para",
    "Nenhum resultado encontrado para": "Ningún resultado encontrado para",

    # ── Admin: users ─────────────────────────────────────────────────────────
    "Gerenciamento de Usuários": "Gestión de Usuarios",
    "Novo Usuário":              "Nuevo Usuario",
    "Usuário":                   "Usuario",
    "Senha":                     "Contraseña",
    "Perfil":                    "Perfil",
    "Viewer (somente leitura)":  "Viewer (solo lectura)",
    "Admin (acesso total)":      "Admin (acceso total)",
    "Criar Usuário":             "Crear Usuario",
    "Usuários Cadastrados":      "Usuarios Registrados",
    "Criado em":                 "Creado el",
    "você":                      "tú",
    "Alterar senha de":          "Cambiar contraseña de",
    "Nova senha":                "Nueva contraseña",

    # ── Admin: brands ────────────────────────────────────────────────────────
    "Informe o domínio da marca para buscar o logo automaticamente via":
        "Indica el dominio de la marca para buscar el logo automáticamente vía",
    "e salvar localmente. Ou faça upload manual de um arquivo PNG/JPG/SVG.":
        "y guardarlo localmente. O sube un archivo PNG/JPG/SVG manualmente.",
    "filamento(s)":              "filamento(s)",
    "ex: bambulab.com":          "ej.: bambulab.com",
    "Upload":                    "Subir",
    "Nenhuma marca cadastrada. Adicione filamentos primeiro.":
        "Ninguna marca registrada. Agrega filamentos primero.",

    # ── Admin: settings ──────────────────────────────────────────────────────
    "Configurações do Sistema":  "Ajustes del Sistema",
    "Geral":                     "General",
    "Moeda":                     "Moneda",
    "Símbolo e formato usados nos preços. Independente do idioma da interface.":
        "Símbolo y formato usados en los precios. Independiente del idioma de la interfaz.",
    "URL Base do Sistema":       "URL Base del Sistema",
    "Usada para gerar o QR code nas etiquetas. Deve ser acessível pelo celular.":
        "Se usa para generar el código QR en las etiquetas. Debe ser accesible desde el móvil.",
    "Threshold (g)":             "Umbral (g)",
    "Threshold (%)":             "Umbral (%)",
    "Peso mínimo antes de sinalizar.": "Peso mínimo antes de avisar.",
    "Porcentagem mínima do nominal.":  "Porcentaje mínimo del nominal.",
    "Etiquetas":                 "Etiquetas",
    "Largura":                   "Ancho",
    "Altura":                    "Alto",
    "Tamanho do PDF gerado para impressão térmica. Padrão:":
        "Tamaño del PDF generado para impresión térmica. Predeterminado:",
    "Fontes e QR code escalam automaticamente.": "Las fuentes y el QR escalan automáticamente.",
    "Impressão Direta (Niimbot)": "Impresión Directa (Niimbot)",
    "Modelo da impressora":      "Modelo de impresora",
    "Tamanho da etiqueta":       "Tamaño de la etiqueta",
    "Usado pelo botão":          "Usado por el botón",
    "(Web Bluetooth, direto do navegador). Requer Chrome/Edge em HTTPS. Não afeta o PDF acima.":
        "(Web Bluetooth, directo desde el navegador). Requiere Chrome/Edge en HTTPS. No afecta al PDF de arriba.",
    "Um item só para todas as Niimbot — o app identifica o modelo conectado (B1, B1 Pro ou M2-H) e envia a resolução certa automaticamente.":
        "Un solo ítem para todas las Niimbot — la app detecta el modelo conectado (B1, B1 Pro o M2-H) y envía la resolución correcta automáticamente.",
    # Niimbot — mensajes del cliente (el driver vendorizado es solo en inglés)
    "identificando impressora…":  "identificando impresora…",
    "imprimindo…":                "imprimiendo…",
    "Impresso":                   "Impreso",
    "Nenhuma impressora selecionada.": "Ninguna impresora seleccionada.",
    "Falha na impressão.":        "Error al imprimir.",
    "Use Chrome ou Edge em HTTPS para imprimir direto na Niimbot.":
        "Usa Chrome o Edge en HTTPS para imprimir directo en la Niimbot.",
    "Impressora não reconhecida ({printer}). Atualize o app ou reporte.":
        "Impresora no reconocida ({printer}). Actualiza la app o repórtalo.",
    "Salvar Configurações":      "Guardar Ajustes",

    # ── Error page ───────────────────────────────────────────────────────────
    "Erro":                      "Error",
    "Voltar ao início":          "Volver al inicio",
    "Acesso negado":             "Acceso denegado",
    "Página não encontrada":     "Página no encontrada",
    "Requisição inválida":              "Solicitud inválida",
    "Erro interno do servidor":         "Error interno del servidor",
    "Erro ao processar. Tente novamente.": "Error al procesar. Por favor intente de nuevo.",

    # ── Spool models ─────────────────────────────────────────────────────────
    "+ Novo Modelo":             "+ Nuevo Modelo",
    "Cadastre os modelos de carretel vazio para que o sistema possa calcular o peso real de filamento disponível.":
        "Registra los modelos de carrete vacío para que el sistema calcule el peso real de filamento disponible.",
    "Tara (g)":                  "Tara (g)",
    "Nenhum modelo cadastrado":  "Ningún modelo registrado",
    "Editar Modelo":             "Editar Modelo",
    "Novo Modelo":               "Nuevo Modelo",
    "Novo Modelo de Carretel":   "Nuevo Modelo de Carrete",
    "ex: Bambu Lab Standard 1kg": "ej.: Bambu Lab Standard 1kg",
    "Peso do Carretel Vazio (g)": "Peso del Carrete Vacío (g)",
    "ex: 250":                   "ej.: 250",
    "Pese o carretel físico sem filamento.": "Pesa el carrete físico sin filamento.",

    # ── Flash / mensagens do servidor ────────────────────────────────────────
    "Sessão expirada ou token inválido. Tente novamente.": "Sesión expirada o token inválido. Inténtalo de nuevo.",
    "Muitas tentativas. Aguarde {min} minutos e tente novamente.": "Demasiados intentos. Espera {min} minutos e inténtalo de nuevo.",
    "Usuário ou senha incorretos": "Usuario o contraseña incorrectos",
    "Filamento cadastrado com sucesso": "Filamento registrado con éxito",
    "Filamento atualizado": "Filamento actualizado",
    "Filamento duplicado — editando cópia": "Filamento duplicado — editando copia",
    "Filamento removido": "Filamento eliminado",
    "Filamento possui spools associados": "El filamento tiene bobinas asociadas",
    "Modelo de carretel cadastrado": "Modelo de carrete registrado",
    "Modelo atualizado": "Modelo actualizado",
    "Modelo removido": "Modelo eliminado",
    "Modelo em uso por spools existentes": "Modelo en uso por bobinas existentes",
    "Rolo cadastrado com sucesso": "Bobina registrada con éxito",
    "Rolo atualizado": "Bobina actualizada",
    "Rolo marcado como finalizado": "Bobina marcada como finalizada",
    "Peso bruto ({g:.0f}g) menor que tara ({t:.0f}g). Verifique.": "Peso bruto ({g:.0f}g) menor que la tara ({t:.0f}g). Verifica.",
    "Peso registrado: {n:.0f}g de filamento": "Peso registrado: {n:.0f}g de filamento",
    "Valor inválido": "Valor inválido",
    "Código de rolo inválido": "Código de bobina inválido",
    "Rolo SP-{code} não encontrado": "Bobina SP-{code} no encontrada",
    "Peso bruto inválido": "Peso bruto inválido",
    "SP-{code} — {n:.0f}g de filamento (bruto {g:.0f}g − tara {t:.0f}g)": "SP-{code} — {n:.0f}g de filamento (bruto {g:.0f}g − tara {t:.0f}g)",
    "Adicionado à fila de impressão": "Agregado a la cola de impresión",
    "{n} rolo(s) adicionado(s) à fila de impressão": "{n} bobina(s) agregada(s) a la cola de impresión",
    "Fila vazia": "Cola vacía",
    "{n} rolo(s) removido(s) da fila": "{n} bobina(s) eliminada(s) de la cola",
    "Fila limpa": "Cola vaciada",
    "Usuário e senha são obrigatórios": "Usuario y contraseña son obligatorios",
    "Usuário já existe": "El usuario ya existe",
    "Usuário {u} criado": "Usuario {u} creado",
    "Senha não pode ser vazia": "La contraseña no puede estar vacía",
    "A senha precisa ter pelo menos {n} caracteres": "La contraseña debe tener al menos {n} caracteres",
    "Senha atualizada": "Contraseña actualizada",
    "Você não pode deletar seu próprio usuário": "No puedes eliminar tu propio usuario",
    "Usuário removido": "Usuario eliminado",
    "Marca e domínio são obrigatórios": "Marca y dominio son obligatorios",
    "Logo de '{brand}' baixado com sucesso": "Logo de '{brand}' descargado con éxito",
    "Não foi possível baixar o logo via Clearbit para '{domain}'": "No se pudo descargar el logo vía Clearbit para '{domain}'",
    "Selecione um arquivo": "Selecciona un archivo",
    "Arquivo inválido": "Archivo inválido",
    "Formato não suportado (PNG, JPG ou WEBP)": "Formato no soportado (PNG, JPG o WEBP)",
    "Logo de '{brand}' salvo": "Logo de '{brand}' guardado",
    "Configurações salvas": "Ajustes guardados",
    "Selecione um arquivo de backup (.zip)": "Selecciona un archivo de copia (.zip)",
    "Arquivo inválido — não é um .zip de backup": "Archivo inválido — no es un .zip de copia",
    "Backup inválido: spool.db ausente no arquivo": "Copia inválida: falta spool.db en el archivo",
    "Backup inválido: o banco não tem a estrutura do Spool Control": "Copia inválida: la base no tiene la estructura de Spool Control",
    "Backup restaurado com sucesso ({n} logo(s)). Recomendado sair e entrar novamente.": "Copia restaurada con éxito ({n} logo(s)). Se recomienda cerrar sesión y volver a entrar.",

    # ── 2FA (verificación en dos pasos) ──────────────────────────────────────
    "Verificação em duas etapas":     "Verificación en dos pasos",
    "Verificar":                      "Verificar",
    "Cancelar":                       "Cancelar",
    "Código de verificação":          "Código de verificación",
    "Código inválido":                "Código inválido",
    "Digite o código de 6 dígitos do seu app autenticador, ou um código de recuperação.":
        "Introduce el código de 6 dígitos de tu app autenticadora, o un código de recuperación.",
    "Verificação em duas etapas ativada":   "Verificación en dos pasos activada",
    "Verificação em duas etapas desativada": "Verificación en dos pasos desactivada",
    "Novos códigos de recuperação gerados": "Nuevos códigos de recuperación generados",
    "Sessão expirada. Tente novamente.":    "Sesión expirada. Inténtalo de nuevo.",
    "Códigos de recuperação":               "Códigos de recuperación",
    "Guarde estes códigos em local seguro. Cada um serve UMA vez se você perder o acesso ao app autenticador. Eles NÃO serão mostrados novamente.":
        "Guarda estos códigos en un lugar seguro. Cada uno sirve UNA vez si pierdes el acceso a tu app autenticadora. NO se mostrarán de nuevo.",
    "A verificação em duas etapas está ativa nesta conta.":
        "La verificación en dos pasos está activa en esta cuenta.",
    "Códigos de recuperação restantes:":    "Códigos de recuperación restantes:",
    "Regenerar códigos de recuperação":     "Regenerar códigos de recuperación",
    "Gera 8 códigos novos e invalida os antigos. Use se acabaram ou se você os perdeu.":
        "Genera 8 códigos nuevos e invalida los anteriores. Úsalo si se agotaron o los perdiste.",
    "Regenerar":                            "Regenerar",
    "Desativar 2FA":                        "Desactivar 2FA",
    "Adicione uma camada extra de segurança ao login: além da senha, será pedido um código gerado por um app autenticador (Google Authenticator, Authy, FreeOTP…).":
        "Añade una capa extra de seguridad al inicio de sesión: además de la contraseña, se pedirá un código generado por una app autenticadora (Google Authenticator, Authy, FreeOTP…).",
    "Ativar verificação em duas etapas":    "Activar verificación en dos pasos",
    "Escaneie o QR Code abaixo com o seu app autenticador.":
        "Escanea el código QR de abajo con tu app autenticadora.",
    "Digite o código de 6 dígitos exibido pelo app para confirmar.":
        "Introduce el código de 6 dígitos que muestra la app para confirmar.",
    "Não consegue escanear? Use esta chave:": "¿No puedes escanear? Usa esta clave:",
    "Ativar":                               "Activar",
    "Copiar códigos":                       "Copiar códigos",
    "Copiado!":                             "¡Copiado!",
    "Proteja sua conta com verificação em duas etapas":
        "Protege tu cuenta con verificación en dos pasos",
    "Você pode ativar agora ou depois, na sua conta.":
        "Puedes activarla ahora o más tarde, en tu cuenta.",
    "Agora não":                            "Ahora no",
    "Ativar agora":                         "Activar ahora",

    # ── Color buckets (stats) ────────────────────────────────────────────────
    "Preto":    "Negro",
    "Branco":   "Blanco",
    "Cinza":    "Gris",
    "Vermelho": "Rojo",
    "Laranja":  "Naranja",
    "Amarelo":  "Amarillo",
    "Verde":    "Verde",
    "Ciano":    "Cian",
    "Azul":     "Azul",
    "Roxo":     "Morado",
    "Rosa":     "Rosa",
    "Marrom":   "Marrón",
}

# PT-BR: só os termos que mudam em relação ao texto-fonte (Spool → Rolo).
_PT = {
    "Spools":               "Rolos",
    "Spool":                "Rolo",
    "Spools Ativos":        "Rolos Ativos",
    "Nenhum spool encontrado": "Nenhum rolo encontrado",
    "Nenhum spool cadastrado": "Nenhum rolo cadastrado",
    "+ Novo Spool":         "+ Novo Rolo",
    "Novo Spool":           "Novo Rolo",
    "Editar Spool":         "Editar Rolo",
    "Finalizar Spool":      "Finalizar Rolo",
    "Marcar spool como finalizado?": "Marcar rolo como finalizado?",
    "Filtrar por Spool":    "Filtrar por Rolo",
    "Todos os spools":      "Todos os rolos",
    "Código do Spool":      "Código do Rolo",
    "Ver todos os spools":  "Ver todos os rolos",
    "Nenhum spool abaixo do threshold configurado.": "Nenhum rolo abaixo do threshold configurado.",
    "Adicione spools pela página de detalhe ou ao cadastrar um novo.":
        "Adicione rolos pela página de detalhe ou ao cadastrar um novo.",
    "Use a barra de busca no topo para pesquisar spools e filamentos.":
        "Use a barra de busca no topo para pesquisar rolos e filamentos.",
    "Detalhe do Spool":     "Detalhe do Rolo",
    "spool(s) vinculado(s) — remova-os antes de excluir":
        "rolo(s) vinculado(s) — remova-os antes de excluir",
}

_EN["Versão demonstrativa"] = "Demo version"
_EN["Os dados são reiniciados diariamente. Senha e criação de usuários não estão disponíveis."] = \
    "Data is reset daily. Password changes and user creation are not available."
_EN["Função desabilitada na versão demonstrativa."] = "This feature is disabled in the demo version."

_ES["Versão demonstrativa"] = "Versión de demostración"
_ES["Os dados são reiniciados diariamente. Senha e criação de usuários não estão disponíveis."] = \
    "Los datos se reinician diariamente. El cambio de contraseña y la creación de usuarios no están disponibles."
_ES["Função desabilitada na versão demonstrativa."] = "Esta función está deshabilitada en la versión de demostración."

# ── Troca de senha (self-service / obrigatória no 1º login) ──────────────────
_EN["Trocar senha"] = "Change password"
_EN["Senha atual"] = "Current password"
_EN["Confirmar nova senha"] = "Confirm new password"
_EN["Salvar nova senha"] = "Save new password"
_EN["Senha atual incorreta"] = "Current password is incorrect"
_EN["As senhas não coincidem"] = "Passwords do not match"
_EN["A nova senha deve ser diferente da atual"] = "The new password must be different from the current one"
_EN["Senha alterada com sucesso"] = "Password changed successfully"
_EN["Por segurança, defina uma senha própria antes de continuar."] = \
    "For security, set your own password before continuing."

_ES["Trocar senha"] = "Cambiar contraseña"
_ES["Senha atual"] = "Contraseña actual"
_ES["Confirmar nova senha"] = "Confirmar nueva contraseña"
_ES["Salvar nova senha"] = "Guardar nueva contraseña"
_ES["Senha atual incorreta"] = "La contraseña actual es incorrecta"
_ES["As senhas não coincidem"] = "Las contraseñas no coinciden"
_ES["A nova senha deve ser diferente da atual"] = "La nueva contraseña debe ser diferente de la actual"
_ES["Senha alterada com sucesso"] = "Contraseña cambiada con éxito"
_ES["Por segurança, defina uma senha própria antes de continuar."] = \
    "Por seguridad, establezca su propia contraseña antes de continuar."

# ── Backup agendado ──────────────────────────────────────────────────────────
_EN["Backup"] = "Backup"
_EN["Pasta de backup externa"] = "External backup folder"
_EN["Caminho no servidor (ex.: disco/rede montado). O backup diário sempre grava localmente; se esta pasta estiver definida, uma cópia também é gravada aqui. Se não for possível gravar, um alerta aparece nesta página."] = \
    "Path on the server (e.g. a mounted disk/network share). The daily backup always writes locally; if this folder is set, a copy is also written here. If writing fails, an alert appears on this page."
_EN["Pasta de backup externa não é gravável: {e}"] = "External backup folder is not writable: {e}"
_EN["Backups automáticos (diários)"] = "Automatic backups (daily)"
_EN["O sistema mantém um backup por dia da semana (7 no total), sobrescrevendo o do mesmo dia a cada semana."] = \
    "The system keeps one backup per weekday (7 total), overwriting the same weekday each week."
_EN["Cópia externa em:"] = "External copy at:"
_EN["Data"] = "Date"
_EN["Tamanho"] = "Size"
_EN["ainda não gerado"] = "not generated yet"
_EN["Restaurar"] = "Restore"
_EN["Backup local não encontrado"] = "Local backup not found"
_EN["Falha ao restaurar o backup"] = "Failed to restore the backup"
_EN["O último backup automático falhou."] = "The last automatic backup failed."
_EN["Backup local OK, mas a cópia para a pasta externa falhou."] = "Local backup OK, but the copy to the external folder failed."

_ES["Backup"] = "Copia de seguridad"
_ES["Pasta de backup externa"] = "Carpeta de backup externa"
_ES["Caminho no servidor (ex.: disco/rede montado). O backup diário sempre grava localmente; se esta pasta estiver definida, uma cópia também é gravada aqui. Se não for possível gravar, um alerta aparece nesta página."] = \
    "Ruta en el servidor (p. ej. un disco/red montado). El backup diario siempre se guarda localmente; si esta carpeta está definida, también se guarda una copia aquí. Si no se puede escribir, aparece una alerta en esta página."
_ES["Pasta de backup externa não é gravável: {e}"] = "La carpeta de backup externa no es escribible: {e}"
_ES["Backups automáticos (diários)"] = "Backups automáticos (diarios)"
_ES["O sistema mantém um backup por dia da semana (7 no total), sobrescrevendo o do mesmo dia a cada semana."] = \
    "El sistema mantiene un backup por día de la semana (7 en total), sobrescribiendo el del mismo día cada semana."
_ES["Cópia externa em:"] = "Copia externa en:"
_ES["Data"] = "Fecha"
_ES["Tamanho"] = "Tamaño"
_ES["ainda não gerado"] = "aún no generado"
_ES["Restaurar"] = "Restaurar"
_ES["Backup local não encontrado"] = "Backup local no encontrado"
_ES["Falha ao restaurar o backup"] = "No se pudo restaurar el backup"
_ES["O último backup automático falhou."] = "El último backup automático falló."
_ES["Backup local OK, mas a cópia para a pasta externa falhou."] = "Backup local OK, pero la copia a la carpeta externa falló."

# ── Integrações / API keys ───────────────────────────────────────────────────
_EN["Integrações"] = "Integrations"
_EN["Chave de API"] = "API key"
_EN["leitura + escrita"] = "read + write"
_EN["somente leitura"] = "read-only"
_EN["habilitada"] = "enabled"
_EN["desabilitada"] = "disabled"
_EN["Habilitar"] = "Enable"
_EN["Desabilitar"] = "Disable"
_EN["Revelar"] = "Reveal"
_EN["Copiar"] = "Copy"
_EN["Último uso:"] = "Last used:"
_EN["Nunca usada"] = "Never used"
_EN["Gerar nova chave"] = "Generate new key"
_EN["Gerar uma nova chave invalida a atual desta integração. Continuar?"] = \
    "Generating a new key invalidates the current one for this integration. Continue?"
_EN["Endpoints (somente leitura)"] = "Endpoints (read-only)"
_EN["Use estes endpoints no Home Assistant (plataforma REST). Passo a passo e exemplos de configuração em"] = \
    "Use these endpoints in Home Assistant (REST platform). Step-by-step and config examples in"
_EN["Integração desconhecida"] = "Unknown integration"
_EN["Nova chave gerada. Atualize a configuração da integração."] = \
    "New key generated. Update the integration's configuration."
_EN["Integração habilitada"] = "Integration enabled"
_EN["Integração desabilitada"] = "Integration disabled"

_ES["Integrações"] = "Integraciones"
_ES["Chave de API"] = "Clave de API"
_ES["leitura + escrita"] = "lectura + escritura"
_ES["somente leitura"] = "solo lectura"
_ES["habilitada"] = "habilitada"
_ES["desabilitada"] = "deshabilitada"
_ES["Habilitar"] = "Habilitar"
_ES["Desabilitar"] = "Deshabilitar"
_ES["Revelar"] = "Revelar"
_ES["Copiar"] = "Copiar"
_ES["Último uso:"] = "Último uso:"
_ES["Nunca usada"] = "Nunca usada"
_ES["Gerar nova chave"] = "Generar nueva clave"
_ES["Gerar uma nova chave invalida a atual desta integração. Continuar?"] = \
    "Generar una nueva clave invalida la actual de esta integración. ¿Continuar?"
_ES["Endpoints (somente leitura)"] = "Endpoints (solo lectura)"
_ES["Use estes endpoints no Home Assistant (plataforma REST). Passo a passo e exemplos de configuração em"] = \
    "Use estos endpoints en Home Assistant (plataforma REST). Paso a paso y ejemplos de configuración en"
_ES["Integração desconhecida"] = "Integración desconocida"
_ES["Nova chave gerada. Atualize a configuração da integração."] = \
    "Nueva clave generada. Actualice la configuración de la integración."
_ES["Integração habilitada"] = "Integración habilitada"
_ES["Integração desabilitada"] = "Integración deshabilitada"

_EN["A atualização está demorando. Recarregue a página em instantes."] = \
    "The update is taking a while. Please reload the page shortly."
_ES["A atualização está demorando. Recarregue a página em instantes."] = \
    "La actualización está tardando. Vuelva a cargar la página en un momento."
_EN["A atualização falhou — o serviço continua na versão atual."] = \
    "The update failed — the service is still on the current version."
_ES["A atualização falhou — o serviço continua na versão atual."] = \
    "La actualización falló — el servicio sigue en la versión actual."

# ── Detalhe do spool / fila de impressão / pesagem rápida (i18n completa) ─────
_EN["Detalhes"] = "Details"
_EN["Ver filamento"] = "View filament"
_EN["Registrar peso"] = "Record weight"
_EN["Etiqueta PDF"] = "PDF label"
_EN["Na fila"] = "In queue"
_EN["+ Fila"] = "+ Queue"
_EN["Registrado por"] = "Recorded by"
_EN["Não"] = "No"
_EN["restante"] = "remaining"
_EN["Carretel"] = "Empty spool"
_EN["Fila de Impressão"] = "Print queue"
_EN["Pesado em"] = "Weighed on"
_EN["Sim, adicionar"] = "Yes, add"
_EN["Imprimir direto na Niimbot (Bluetooth)"] = "Print directly on Niimbot (Bluetooth)"
_EN["Imprimir a fila direto na Niimbot (Bluetooth)"] = "Print the queue directly on Niimbot (Bluetooth)"
_EN["Tara efetiva"] = "Effective tare"
_EN["Tara (g)"] = "Tare (g)"
_EN["Compra"] = "Purchase"
_EN["Não pesado ainda"] = "Not weighed yet"
_EN["Remover da fila de impressão"] = "Remove from print queue"
_EN["Adicionar à fila de impressão"] = "Add to print queue"
_EN["de {n}g nominais"] = "of {n}g nominal"
_EN["Deseja adicionar"] = "Add"
_EN["à fila de impressão de etiquetas?"] = "to the label print queue?"
_EN["Remover todos da fila"] = "Remove all from queue"
_EN["Adicionar todos à fila"] = "Add all to queue"
_EN["SP-0001 ou 1"] = "SP-0001 or 1"
_EN["ex: 1150"] = "e.g. 1150"

_ES["Detalhes"] = "Detalles"
_ES["Ver filamento"] = "Ver filamento"
_ES["Registrar peso"] = "Registrar peso"
_ES["Etiqueta PDF"] = "Etiqueta PDF"
_ES["Na fila"] = "En cola"
_ES["+ Fila"] = "+ Cola"
_ES["Registrado por"] = "Registrado por"
_ES["Não"] = "No"
_ES["restante"] = "restante"
_ES["Carretel"] = "Bobina vacía"
_ES["Fila de Impressão"] = "Cola de impresión"
_ES["Pesado em"] = "Pesado el"
_ES["Sim, adicionar"] = "Sí, agregar"
_ES["Imprimir direto na Niimbot (Bluetooth)"] = "Imprimir directo en Niimbot (Bluetooth)"
_ES["Imprimir a fila direto na Niimbot (Bluetooth)"] = "Imprimir la cola directo en Niimbot (Bluetooth)"
_ES["Tara efetiva"] = "Tara efectiva"
_ES["Tara (g)"] = "Tara (g)"
_ES["Compra"] = "Compra"
_ES["Não pesado ainda"] = "Aún no pesado"
_ES["Remover da fila de impressão"] = "Quitar de la cola de impresión"
_ES["Adicionar à fila de impressão"] = "Agregar a la cola de impresión"
_ES["de {n}g nominais"] = "de {n}g nominales"
_ES["Deseja adicionar"] = "Agregar"
_ES["à fila de impressão de etiquetas?"] = "a la cola de impresión de etiquetas?"
_ES["Remover todos da fila"] = "Quitar todos de la cola"
_ES["Adicionar todos à fila"] = "Agregar todos a la cola"
_ES["SP-0001 ou 1"] = "SP-0001 o 1"
_ES["ex: 1150"] = "ej: 1150"

_TABLES = {"en": _EN, "es": _ES, "pt": _PT}


def get_translator(lang: str):
    table = _TABLES.get(lang, {})

    def _(s: str) -> str:
        return table.get(s, s)

    return _
