[env:balanca-c3]
platform  = espressif32
board     = esp32-c3-devkitm-1
framework = arduino

; ESP32-C3 SuperMini — USB-CDC nativo
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DDEBUG

build_src_filter = -<*> +<main_balanca.cpp>

board_build.partitions = min_spiffs.csv

upload_port   = COM23
monitor_port  = COM23
monitor_speed = 115200
upload_speed  = 921600

lib_deps =
    olikraus/U8g2 @ ^2
    bogde/HX711 @ ^0.7.5
    fastled/FastLED @ ^3.6
